"""
gap_bridge.py — Generate, run, and high-level orchestration for SgpDec holonomy decompositions.

This module is the "GAP bridge" service:
- Turn a list of transformation images into a self-contained GAP script
  (uses SgpDec's HolonomyCascadeSemigroup).
- Execute the script via subprocess (gap --no-window --bare).
- Provide the high-level API (decompose_gens / decompose_aut) that wires
  extraction + generation + execution + (via kr.gap.parse) result parsing.

Parsing of the structured GAP output lives in the focused sibling
kr/gap/parse.py (small file, easy to test in isolation, produces Cascade).

The generated script uses easy-to-parse Print statements (CASCADE_START /
KEY: value + STATE ... CONFIG lines). This keeps the Python side robust
against small changes in SgpDec pretty-printers.

See also:
- kr/gap/parse.py : the output parser service
- kr/cascade.py   : the result data model + config automaton helpers
- kr/extract.py   : Spot aut -> generator images (assumes complete deterministic input)
"""

from __future__ import annotations
import os
import subprocess
import tempfile
from pathlib import Path
from typing import List, Optional

from .cascade import Cascade, LevelInfo
from .extract import extract_generators, ExtractionError, is_deterministic
from .gap.parse import parse_cascade_output  # focused parser service (keeps this file smaller)

import spot


# ---------------------------------------------------------------------------
# GAP script generation
# ---------------------------------------------------------------------------

def _format_transformation(images: List[int]) -> str:
    """Return GAP source for Transformation([1-based images...])."""
    # GAP Transformations are 1-based.
    one_based = [i + 1 for i in images]
    return f"Transformation({one_based})"


def generate_gap_script(
    generators: List[List[int]],
    *,
    title: str = "BuchiToLTL KR decomposition",
    max_runtime_seconds: int = 120,
) -> str:
    """
    Produce a complete, self-contained GAP script.

    The script:
      1. Loads SgpDec (fails loudly if missing).
      2. Builds the semigroup from the generators.
      3. Computes the holonomy cascade.
      4. Emits a structured block that is easy to parse from Python.

    The caller is responsible for writing the script to disk and running `gap`.
    """
    if not generators:
        raise ValueError("At least one generator is required")

    n = len(generators[0])
    for g in generators:
        if len(g) != n:
            raise ValueError("All generators must have the same domain size")

    lines: List[str] = []
    lines.append('########################################################################')
    lines.append(f'# {title}')
    lines.append('# Auto-generated by BuchiToLTL/kr/gap_bridge.py')
    lines.append('# Do not edit by hand — re-run the Python generator instead.')
    lines.append('########################################################################')
    lines.append('')
    lines.append('LoadPackage("SgpDec");')
    lines.append('')
    lines.append('# === Generated generators (1-based images for GAP) ===')
    lines.append('gens := [')
    for i, g in enumerate(generators):
        comma = "," if i < len(generators) - 1 else ""
        lines.append(f'    {_format_transformation(g)}{comma}   # letter {i}')
    lines.append('];')
    lines.append('')
    lines.append('T := Semigroup(gens);')
    lines.append(f'n_states := {n};   # reliable domain size from generator images (SgpDec Degree may be 0 for 1-el)')
    lines.append('Print("SEMI_GROUP_SIZE: ", Size(T), "\\n");')
    lines.append('Print("NUM_STATES: ", n_states, "\\n");')
    lines.append('')
    lines.append('# === Holonomy cascade (the expensive step) ===')
    lines.append('# Guard: SgpDec HolonomyCascadeSemigroup can crash or misreport Degree=0 on 1-state (trivial) TS.')
    lines.append('if n_states <= 1 then')
    lines.append('  # Trivial case handled below without calling Holonomy.')
    lines.append('else')
    lines.append('  hcs := HolonomyCascadeSemigroup(T);')
    lines.append('fi;')
    lines.append('')
    lines.append('Print("CASCADE_START\\n");')
    lines.append('')
    lines.append('# Robust extraction for SgpDec 1.x (no reliance on internal !.Levels record).')
    lines.append('# Number of levels = length of a coordinate tuple.')
    lines.append('n := n_states;')
    lines.append('if n <= 1 then')
    lines.append('  if n = 0 then')
    lines.append('    Print("NUM_LEVELS: 0\\n");')
    lines.append('  else')
    lines.append('    # Trivial 1-state cascade: 1 level, coord [1] (1-based as SgpDec uses).')
    lines.append('    Print("NUM_LEVELS: 1\\n");')
    lines.append('    Print("LEVEL 0 SIZE 1 KIND reset\\n");')
    lines.append('    Print("STATE_MAP_START\\n");')
    lines.append('    Print("STATE 0 CONFIG [ 1 ]\\n");')
    lines.append('    Print("STATE_MAP_END\\n");')
    lines.append('  fi;')
    lines.append('else')
    lines.append('  sample_coord := AsCoords(1, hcs);')
    lines.append('  num_lev := Length(sample_coord);')
    lines.append('  all_coords := List([1..n], s -> AsCoords(s, hcs));')
    lines.append('  Print("NUM_LEVELS: ", num_lev, "\\n");')
    lines.append('  # Per-level sizes: max coordinate value at that position (1-based coords)')
    lines.append('  for lev in [1..num_lev] do')
    lines.append('    sz := Maximum( List(all_coords, c -> c[lev]) );')
    lines.append('    Print("LEVEL ", lev-1, " SIZE ", sz, " KIND reset\\n");')
    lines.append('  od;')
    lines.append('  # State -> configuration mapping (the key data for later LTL synthesis)')
    lines.append('  Print("STATE_MAP_START\\n");')
    lines.append('  for s in [1..n] do')
    lines.append('    coord := all_coords[s];')
    lines.append('    Print("STATE ", s-1, " CONFIG ", coord, "\\n");')
    lines.append('  od;')
    lines.append('  Print("STATE_MAP_END\\n");')
    lines.append('fi;')
    lines.append('')
    lines.append('Print("CASCADE_END\\n");')
    lines.append('')
    lines.append('# Friendly one-liner for humans')
    lines.append('if n_states > 0 then')
    lines.append('  if n_states <= 1 then')
    lines.append('    Print("Holonomy cascade ready (trivial 1-state).\\n");')
    lines.append('  else')
    lines.append('    sample := AsCoords(1, hcs);')
    lines.append('    Print("Holonomy cascade ready. Levels: ", Length(sample), "\\n");')
    lines.append('  fi;')
    lines.append('else')
    lines.append('  Print("Holonomy cascade ready (trivial).\\n");')
    lines.append('fi;')
    lines.append('QUIT;')
    lines.append('')

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Running GAP
# ---------------------------------------------------------------------------

def run_gap_script(
    script: str,
    *,
    gap_cmd: str = "gap",
    timeout: int = 180,
    workdir: Optional[Path] = None,
) -> str:
    """
    Write `script` to a temp file and execute `gap --no-window <script>`.

    Returns the captured stdout.  Stderr is logged but not returned.
    Raises on non-zero exit or timeout.
    """
    with tempfile.TemporaryDirectory(dir=workdir) as td:
        script_path = Path(td) / "decompose.gap"
        out_path = Path(td) / "cascade.out"

        script_path.write_text(script, encoding="utf-8")

        cmd = [gap_cmd, "--no-window", "--bare", str(script_path)]
        try:
            with open(out_path, "w", encoding="utf-8") as out_f:
                proc = subprocess.run(
                    cmd,
                    stdout=out_f,
                    stderr=subprocess.PIPE,
                    timeout=timeout,
                    check=False,
                    text=True,
                )
            captured = out_path.read_text(encoding="utf-8")
            if proc.returncode != 0:
                raise RuntimeError(
                    f"GAP exited with code {proc.returncode}.\n"
                    f"stderr (last 2000 chars):\n{proc.stderr[-2000:]}\n"
                    f"stdout head:\n{captured[:1500]}"
                )
            return captured
        except subprocess.TimeoutExpired:
            raise RuntimeError(f"GAP run timed out after {timeout}s") from None


# Parsing is now in the focused kr/gap/parse.py service (keeps this file smaller
# and gives the parser its own small, testable home).
# We re-export the name here for backward compatibility with any code that
# did "from kr.gap_bridge import parse_cascade_output".
from .gap.parse import parse_cascade_output  # noqa: F401


# ---------------------------------------------------------------------------
# High-level convenience API
# ---------------------------------------------------------------------------

def decompose_gens(
    generators: List[List[int]],
    *,
    gap_cmd: str = "gap",
    timeout: int = 180,
) -> Cascade:
    """Run the full pipeline on an explicit list of generator images."""
    script = generate_gap_script(generators)
    raw = run_gap_script(script, gap_cmd=gap_cmd, timeout=timeout)
    return parse_cascade_output(raw, generators=generators)


def decompose_aut(
    aut: "spot.twa_graph",
    *,
    gap_cmd: str = "gap",
    timeout: int = 180,
    max_aps: int = 5,
) -> Cascade:
    """
    End-to-end: caller aut → Spot normalization to a deterministic complete
    minimized parity automaton (min even, via postprocess "parity min even",
    "deterministic", "complete") → generators → GAP (SgpDec holonomy) → Cascade.

    IMPORTANT (per current design): Spot transformations (including any state
    additions for determinization/completion/minimization) are expected and
    normal. The resulting deterministic automaton *is* the authoritative input
    D for the rest of the algorithm (Krohn-Rhodes decomp, reachability formulas,
    Fin(C), Muller DNF assembly). The homomorphism h (state_to_config) and
    acceptance lifting are defined with respect to *this* D's states and
    acceptance condition.

    The caller's original (possibly non-det, Buchi-style) aut is *not* used
    for the construction. Callers should keep it aside themselves only if
    they want a final language-equivalence check (spot.are_equivalent) after
    reconstruction. The LTL we produce is for the language of the normalized D
    (which is equivalent to the original by Spot's postprocess guarantees).

    Completion (and determinization if needed) is handled by Spot; any sink
    that appears is just a normal state. The algebraic construction treats
    everything uniformly via configs. No manual dead-trap.

    This is the standardized input contract for the KR path.
    """
    # Normalize to deterministic complete minimized parity using Spot.
    # This normalized det aut *is* our working D for decomp + reachability + Fin + assembly.
    # "sbacc" (state-based acceptance) is required for soundness: the Muller
    # condition we lift is over configurations (states), so the set of
    # infinitely-visited states must determine acceptance. With Spot's default
    # transition-based marks, a state can carry both accepting and rejecting
    # out-edges (e.g. the 1-state DPA for GFa), and the state-level Muller view
    # cannot distinguish accepting from rejecting runs.
    aut = spot.postprocess(aut, "parity min even", "deterministic", "complete", "sbacc")

    if not is_deterministic(aut):
        raise ExtractionError(
            "decompose_aut requires a deterministic automaton. "
            "The input could not be determinized to parity."
        )

    gens, masks, valuations = extract_generators(aut, max_aps=max_aps)
    casc = decompose_gens(gens, gap_cmd=gap_cmd, timeout=timeout)
    # Enrich the cascade with letter/valuation data needed for LTL encoding
    casc.aps = [str(ap) for ap in aut.ap()]
    casc.letter_masks = masks
    casc.letter_valuations = valuations
    casc.original_aut = aut  # the normalized det parity aut (our D)
    return casc


def check_gap_available(gap_cmd: str = "gap") -> bool:
    """Return True iff a runnable GAP that can LoadPackage("SgpDec") exists."""
    try:
        out = subprocess.run(
            [gap_cmd, "--no-window", "--bare", "-c",
             'if LoadPackage("SgpDec")=fail then Print("NO\n"); else Print("YES\n"); fi; QUIT;'],
            capture_output=True, text=True, timeout=15
        )
        return "YES" in out.stdout
    except Exception:
        return False
