"""
gap_bridge.py — Generate, run, and parse SgpDec holonomy decompositions from Python.

This module implements the "first integration steps" of the plan:
- Turn a list of transformation images into a self-contained GAP script that
  uses SgpDec's HolonomyCascadeSemigroup.
- Execute it via subprocess (gap --no-window).
- Parse the structured textual output we asked the script to emit into a
  `Cascade` Python object.

The generated script is deliberately verbose and uses easy-to-parse Print
statements (CASCADE_START / KEY: value style).  This makes the Python side
robust against small changes in SgpDec's Display* pretty printers.

We also provide a convenience entry point `decompose_aut(spot_aut)` that
combines extraction + GAP round-trip.
"""

from __future__ import annotations
import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import List, Optional

from .cascade import Cascade, LevelInfo
from .extract import extract_generators, ExtractionError, is_deterministic


# ---------------------------------------------------------------------------
# GAP script generation
# ---------------------------------------------------------------------------

def _format_transformation(images: List[int]) -> str:
    """Return GAP source for Transformation([1-based images...])."""
    # GAP Transformations are 1-based.
    one_based = [i + 1 for i in images]
    return f"Transformation({one_based})"


def generate_gap_script(
    generators: List[List[int]],
    *,
    title: str = "BuchiToLTL KR decomposition",
    max_runtime_seconds: int = 120,
) -> str:
    """
    Produce a complete, self-contained GAP script.

    The script:
      1. Loads SgpDec (fails loudly if missing).
      2. Builds the semigroup from the generators.
      3. Computes the holonomy cascade.
      4. Emits a structured block that is easy to parse from Python.

    The caller is responsible for writing the script to disk and running `gap`.
    """
    if not generators:
        raise ValueError("At least one generator is required")

    n = len(generators[0])
    for g in generators:
        if len(g) != n:
            raise ValueError("All generators must have the same domain size")

    lines: List[str] = []
    lines.append('########################################################################')
    lines.append(f'# {title}')
    lines.append('# Auto-generated by BuchiToLTL/kr/gap_bridge.py')
    lines.append('# Do not edit by hand — re-run the Python generator instead.')
    lines.append('########################################################################')
    lines.append('')
    lines.append('LoadPackage("SgpDec");')
    lines.append('')
    lines.append('# === Generated generators (1-based images for GAP) ===')
    lines.append('gens := [')
    for i, g in enumerate(generators):
        comma = "," if i < len(generators) - 1 else ""
        lines.append(f'    {_format_transformation(g)}{comma}   # letter {i}')
    lines.append('];')
    lines.append('')
    lines.append('T := Semigroup(gens);')
    lines.append('Print("SEMI_GROUP_SIZE: ", Size(T), "\\n");')
    lines.append('Print("NUM_STATES: ", DegreeOfTransformationSemigroup(T), "\\n");')
    lines.append('')
    lines.append('# === Holonomy cascade (the expensive step) ===')
    lines.append('hcs := HolonomyCascadeSemigroup(T);')
    lines.append('')
    lines.append('Print("CASCADE_START\\n");')
    lines.append('')
    lines.append('# Robust extraction for SgpDec 1.x (no reliance on internal !.Levels record).')
    lines.append('# Number of levels = length of a coordinate tuple.')
    lines.append('n := DegreeOfTransformationSemigroup(T);')
    lines.append('if n = 0 then')
    lines.append('  Print("NUM_LEVELS: 0\\n");')
    lines.append('else')
    lines.append('  sample_coord := AsCoords(1, hcs);')
    lines.append('  num_lev := Length(sample_coord);')
    lines.append('  if num_lev = 0 and n = 1 then')
    lines.append('    # Trivial 1-state case')
    lines.append('    num_lev := 1;')
    lines.append('    all_coords := [ [1] ];')
    lines.append('  else')
    lines.append('    all_coords := List([1..n], s -> AsCoords(s, hcs));')
    lines.append('  fi;')
    lines.append('  Print("NUM_LEVELS: ", num_lev, "\\n");')
    lines.append('  # Per-level sizes: max coordinate value at that position (1-based coords)')
    lines.append('  for lev in [1..num_lev] do')
    lines.append('    sz := Maximum( List(all_coords, c -> c[lev]) );')
    lines.append('    Print("LEVEL ", lev-1, " SIZE ", sz, " KIND reset\\n");')
    lines.append('  od;')
    lines.append('  # State -> configuration mapping (the key data for later LTL synthesis)')
    lines.append('  Print("STATE_MAP_START\\n");')
    lines.append('  for s in [1..n] do')
    lines.append('    coord := all_coords[s];')
    lines.append('    Print("STATE ", s-1, " CONFIG ", coord, "\\n");')
    lines.append('  od;')
    lines.append('  Print("STATE_MAP_END\\n");')
    lines.append('fi;')
    lines.append('')
    lines.append('Print("CASCADE_END\\n");')
    lines.append('')
    lines.append('# Friendly one-liner for humans')
    lines.append('if n > 0 then')
    lines.append('  sample := AsCoords(1, hcs);')
    lines.append('  Print("Holonomy cascade ready. Levels: ", Length(sample), "\\n");')
    lines.append('else')
    lines.append('  Print("Holonomy cascade ready (trivial).\\n");')
    lines.append('fi;')
    lines.append('QUIT;')
    lines.append('')

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Running GAP
# ---------------------------------------------------------------------------

def run_gap_script(
    script: str,
    *,
    gap_cmd: str = "gap",
    timeout: int = 180,
    workdir: Optional[Path] = None,
) -> str:
    """
    Write `script` to a temp file and execute `gap --no-window <script>`.

    Returns the captured stdout.  Stderr is logged but not returned.
    Raises on non-zero exit or timeout.
    """
    with tempfile.TemporaryDirectory(dir=workdir) as td:
        script_path = Path(td) / "decompose.gap"
        out_path = Path(td) / "cascade.out"

        script_path.write_text(script, encoding="utf-8")

        cmd = [gap_cmd, "--no-window", "--bare", str(script_path)]
        try:
            with open(out_path, "w", encoding="utf-8") as out_f:
                proc = subprocess.run(
                    cmd,
                    stdout=out_f,
                    stderr=subprocess.PIPE,
                    timeout=timeout,
                    check=False,
                    text=True,
                )
            captured = out_path.read_text(encoding="utf-8")
            if proc.returncode != 0:
                raise RuntimeError(
                    f"GAP exited with code {proc.returncode}.\n"
                    f"stderr (last 2000 chars):\n{proc.stderr[-2000:]}\n"
                    f"stdout head:\n{captured[:1500]}"
                )
            return captured
        except subprocess.TimeoutExpired:
            raise RuntimeError(f"GAP run timed out after {timeout}s") from None


# ---------------------------------------------------------------------------
# Parsing the structured output
# ---------------------------------------------------------------------------

_STATE_LINE = re.compile(r"^STATE\s+(\d+)\s+CONFIG\s+\[([^\]]*)\]", re.MULTILINE)
_LEVEL_LINE = re.compile(r"^LEVEL\s+(\d+)\s+SIZE\s+(\d+)\s+KIND\s+(\S+)(?:\s+STRUCT\s+(\S+))?", re.MULTILINE)
_NUM_LEVELS = re.compile(r"^NUM_LEVELS:\s*(\d+)", re.MULTILINE)
_NUM_STATES = re.compile(r"^NUM_STATES:\s*(\d+)", re.MULTILINE)
_SEMI_SIZE = re.compile(r"^SEMI_GROUP_SIZE:\s*(\d+)", re.MULTILINE)


def parse_cascade_output(raw: str, generators: Optional[List[List[int]]] = None) -> Cascade:
    """Parse the CASCADE_START ... CASCADE_END block (and surrounding keys)."""
    # We are tolerant: we look for the markers but also accept data outside them.
    m_nl = _NUM_LEVELS.search(raw)
    num_levels = int(m_nl.group(1)) if m_nl else 0

    m_ns = _NUM_STATES.search(raw)
    num_states = int(m_ns.group(1)) if m_ns else 0

    levels: List[LevelInfo] = []
    for m in _LEVEL_LINE.finditer(raw):
        idx = int(m.group(1))
        sz = int(m.group(2))
        kind = m.group(3)
        struct = m.group(4)
        levels.append(LevelInfo(index=idx, size=sz, kind=kind, structure=struct))

    if not num_levels and levels:
        num_levels = len(levels)

    state_to_config: dict[int, tuple[int, ...]] = {}
    for m in _STATE_LINE.finditer(raw):
        s = int(m.group(1))
        coord_str = m.group(2).strip()
        if coord_str:
            coords = tuple(int(x.strip()) for x in coord_str.split(","))
        else:
            coords = tuple()
        state_to_config[s] = coords

    # Build reverse map (last write wins if collisions — rare)
    config_to_state: dict[tuple[int, ...], int] = {
        cfg: st for st, cfg in state_to_config.items()
    }

    meta = {}
    m_ss = _SEMI_SIZE.search(raw)
    if m_ss:
        meta["semigroup_size"] = int(m_ss.group(1))

    if "CASCADE_START" not in raw or "CASCADE_END" not in raw:
        # Still try to return what we got; the caller can decide if it's usable.
        meta["warning"] = "CASCADE markers not found — partial parse"

    return Cascade(
        num_levels=num_levels or len(levels),
        levels=levels,
        num_states=num_states or len(state_to_config),
        state_to_config=state_to_config,
        config_to_state=config_to_state,
        generator_images=generators or [],
        raw_output=raw,
        metadata=meta,
    )


# ---------------------------------------------------------------------------
# High-level convenience API
# ---------------------------------------------------------------------------

def decompose_gens(
    generators: List[List[int]],
    *,
    gap_cmd: str = "gap",
    timeout: int = 180,
) -> Cascade:
    """Run the full pipeline on an explicit list of generator images."""
    script = generate_gap_script(generators)
    raw = run_gap_script(script, gap_cmd=gap_cmd, timeout=timeout)
    return parse_cascade_output(raw, generators=generators)


def decompose_aut(
    aut: "spot.twa_graph",
    *,
    gap_cmd: str = "gap",
    timeout: int = 180,
    max_aps: int = 5,
) -> Cascade:
    """
    End-to-end: deterministic Spot aut → generators → GAP → Cascade.

    The automaton must be deterministic (see extract.is_deterministic).
    """
    if not is_deterministic(aut):
        raise ExtractionError(
            "decompose_aut expects a deterministic automaton. "
            "Translate with 'Deterministic' or call determinize()."
        )
    gens, _masks = extract_generators(aut, max_aps=max_aps)
    return decompose_gens(gens, gap_cmd=gap_cmd, timeout=timeout)


def check_gap_available(gap_cmd: str = "gap") -> bool:
    """Return True iff a runnable GAP that can LoadPackage("SgpDec") exists."""
    try:
        out = subprocess.run(
            [gap_cmd, "--no-window", "--bare", "-c",
             'if LoadPackage("SgpDec")=fail then Print("NO\n"); else Print("YES\n"); fi; QUIT;'],
            capture_output=True, text=True, timeout=15
        )
        return "YES" in out.stdout
    except Exception:
        return False
