"""The stutter-invariance read-off — an equational property of the syntactic
monoid, the structural twin of the aperiodicity (LTL) read-off.

A language is **stutter-invariant** (closed under doubling/collapsing adjacent
equal letters) iff its syntactic monoid keeps no letter apart from its own
square: every letter's class is idempotent, ``M(λ(a), λ(a)) = λ(a)``. Then no
fold can tell ``a`` from ``aa``, hence no context can, so membership is
stutter-blind (paper Prop 3.3). Like aperiodicity this is a one-line equational
test on the generators, independent of the accepting set; on the *syntactic*
invariant (the canonical form the corpus stores) it is exactly the language
property, since a non-idempotent letter is one the syntactic congruence keeps
apart from its square — a genuine ``a``/``aa`` separation.

Independent of aperiodicity: a monoid generated by idempotent letters may still
contain a group, so the two classifications cross-tabulate non-trivially.
Normative math: `research_notes/sos_classification.md` (Prop 3.3).
"""
from __future__ import annotations

from ..invariant import Invariant


def is_stutter_invariant(inv: Invariant) -> bool:
    """Is ``L`` stutter-invariant, for every accepting set over ``inv``'s
    algebra? True iff each letter's class is idempotent — the read-off above.
    A property of the algebra ``(Σ, λ, M)``; ``inv.accept`` is not consulted."""
    mult = inv.mult
    return all(mult[la][la] == la for la in inv.letter_class)
