"""The recognizer, materialized: the closed enriched monoid ``EM1(D)``.

BFS from the letter elements under right-multiplication, identity adjoined,
up to a size budget. The result carries everything the congruence computation
consumes downstream: the element set, one shortest representative word per
element (letters in alphabet mask order, so representatives are met in
shortlex order), and the right-multiplication table
``element x letter -> element``.

Pure: the budget is a parameter, blowing it returns ``None`` (the caller owns
the policy of what that means).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from .enriched import Elem, compose, identity_elem


@dataclass
class Monoid:
    """The closed enriched monoid ``EM1(D)``, indexed form.

    Element 0 is the identity (the empty word). ``rep[i]`` is a shortest word
    for element ``i``, as letter masks in the alphabet order the closure was
    built from. ``right[i][a]`` is the index of ``elems[i] . letter a`` —
    total over all elements and letters."""

    elems: List[Elem]
    index: Dict[Elem, int]
    rep: List[List[int]]
    right: List[List[int]]

    def __len__(self) -> int:
        return len(self.elems)

    def mult(self, i: int, j: int) -> int:
        """The index of ``elems[i] . elems[j]`` (one ``O(|Q|)`` composition
        plus a hash lookup — never a word fold)."""
        return self.index[compose(self.elems[i], self.elems[j])]


def close(letters: List[Elem], n_states: int, cap: int) -> Optional[Monoid]:
    """BFS-close the monoid generated by ``letters`` (identity adjoined),
    keeping one shortest representative per element, or ``None`` when more
    than ``cap`` elements appear. Elements are met shortest-first in letter
    order, so ``rep[i]`` is the shortlex-least word of element ``i``."""
    identity: Elem = identity_elem(n_states)
    elems: List[Elem] = [identity]
    index: Dict[Elem, int] = {identity: 0}
    rep: List[List[int]] = [[]]
    right: List[List[int]] = []
    i = 0
    while i < len(elems):
        row: List[int] = []
        for a, le in enumerate(letters):
            ne = compose(elems[i], le)
            j = index.get(ne)
            if j is None:
                if len(elems) >= cap:
                    return None
                j = len(elems)
                index[ne] = j
                elems.append(ne)
                rep.append(rep[i] + [a])
            row.append(j)
        right.append(row)
        i += 1
    return Monoid(elems=elems, index=index, rep=rep, right=right)


__all__ = ["Monoid", "close"]
