"""The invariant I(L) = (C, key, lambda, M, P), and the membership read-off.

The finite algebraic normal form of an omega-regular language:

  - classes ``C`` are the integers ``0..n-1``; one of them, ``identity``, is the
    adjoined monoid unit (the class of the empty word);
  - ``keys[c]`` is the shortlex-least word of class ``c`` (its canonical name);
  - ``letter_class[a]`` is the class of the single-letter word ``a`` (lambda),
    indexed by letter mask;
  - ``mult[a][b]`` is the class of ``key(a).key(b)`` (M), the class product;
  - ``accept`` is the set of accepting linked pairs P: pairs ``(s, e)`` with
    ``mult[e][e] == e`` and ``mult[s][e] == s``.

Membership of any lasso is decided from this tuple alone (see `member`), with no
automaton. The construction of a valid instance is the job of the builders
(`sosl.reference`, or the learner's export); this module only holds one and
reads it.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import FrozenSet, List, Tuple

from sosl.objects.alphabet import EMPTY, Alphabet, Word
from sosl.objects.lasso import Lasso


@dataclass(frozen=True)
class Invariant:
    """One invariant I(L); see the module docstring for the field contract."""

    alphabet: Alphabet
    keys: Tuple[Word, ...]
    letter_class: Tuple[int, ...]
    mult: Tuple[Tuple[int, ...], ...]
    accept: FrozenSet[Tuple[int, int]]
    identity: int

    @property
    def n(self) -> int:
        """The number of classes."""
        return len(self.keys)

    def fold(self, word: Word) -> int:
        """The class of ``word``: the left-to-right product of its letters'
        classes, starting from the identity (so the empty word folds to
        ``identity``)."""
        c = self.identity
        for a in word:
            c = self.mult[c][self.letter_class[a]]
        return c

    def idempotent_power(self, c: int) -> int:
        """The idempotent ``c^omega`` in the subsemigroup generated by ``c``:
        the unique power ``e = c^i`` with ``mult[e][e] == e``. Found as the
        least ``i >= 1`` with ``c^i == c^{2i}`` (``i <= n`` always)."""
        n = self.n
        powers: List[int] = [c, c]  # index 0 unused; powers[1] = c^1
        p = c
        for _ in range(2 * n):
            p = self.mult[p][c]
            powers.append(p)
        for i in range(1, n + 1):
            if powers[i] == powers[2 * i]:
                return powers[i]
        raise ValueError("no idempotent power (malformed multiplication table)")

    def member(self, lasso: Lasso) -> bool:
        """Is ``lasso`` in the language? Fold stem and loop to classes, iterate
        the loop class to its idempotent ``e``, absorb one loop into the stem
        (``s = [stem].e``), and accept iff ``(s, e)`` is a linked pair in P."""
        cu = self.fold(lasso.stem)
        cv = self.fold(lasso.loop)
        e = self.idempotent_power(cv)
        s = self.mult[cu][e]
        return (s, e) in self.accept

    def linked_pairs(self) -> FrozenSet[Tuple[int, int]]:
        """All linked pairs ``(s, e)``: ``e`` idempotent and ``mult[s][e] == s``.
        The accepting set ``accept`` is a subset of these."""
        pairs = []
        for e in range(self.n):
            if self.mult[e][e] != e:
                continue
            for s in range(self.n):
                if self.mult[s][e] == s:
                    pairs.append((s, e))
        return frozenset(pairs)

    def validate(self) -> None:
        """Assert the structural laws: identity is the empty word's class and a
        two-sided unit, the table is a closed n x n array of class ids, and
        every accepting pair is a linked pair. Raises AssertionError on the
        first violation."""
        n = self.n
        assert 0 <= self.identity < n, self.identity
        assert self.keys[self.identity] == EMPTY, self.keys[self.identity]
        assert len(self.letter_class) == self.alphabet.size
        assert all(0 <= c < n for c in self.letter_class)
        assert len(self.mult) == n, len(self.mult)
        for row in self.mult:
            assert len(row) == n and all(0 <= v < n for v in row)
        for x in range(n):
            assert self.mult[self.identity][x] == x, x
            assert self.mult[x][self.identity] == x, x
        linked = self.linked_pairs()
        for pair in self.accept:
            assert pair in linked, pair
