"""The TikZ backend: a placed `Figure` as a standalone `.tex` a human can edit.

The output is written to be *nudged*: every visual choice lives in one `\\tikzset`
block (`class`, `root`, `idem`, `letter <x>`, `tree`, `nontree`, `cyc`), each node
is a named `\\node` at an explicit rounded coordinate, each edge is one `\\draw`
between node names. Changing how the figure looks means editing one style;
changing where a node sits means editing one coordinate. Nothing is styled inline
and nothing is repeated.

Pure text: the placement is an input (see `layout.py`), not something computed
here.
"""
from __future__ import annotations

from typing import Dict, List, Tuple

from .layout import Placement
from .model import Figure

# The dash pattern per letter index; cycled if the alphabet is larger.
LETTER_DASH = ("solid", "dashed", "dotted", "densely dashdotted")
# Self-loop directions, in preference order, with the unit vector each points at.
LOOP_DIRS: Tuple[Tuple[str, Tuple[float, float]], ...] = (
    ("loop above", (0.0, 1.0)), ("loop below", (0.0, -1.0)),
    ("loop right", (1.0, 0.0)), ("loop left", (-1.0, 0.0)))
# A neighbour nearer than this (cm), in a direction's cone, crowds it out.
CROWD_CM = 2.6
# Bend angles for the i-th of several edges joining the same two nodes.
BEND_BASE, BEND_STEP = 12, 18
# How far under the lowest node the P caption sits (cm).
PAIRS_DROP_CM = 1.3


def _tex_key(fig: Figure, key: Tuple[int, ...]) -> str:
    """The math body of a display key: letters joined by ``{\\cdot}``, the identity
    as ``\\varepsilon``. No ``$`` — the caller places it."""
    if not key:
        return r"\varepsilon"
    names = [fig.naming.names[i] for i in key]
    escaped = [n.replace("!", r"\lnot ").replace("&", r"\wedge ") for n in names]
    return r"{\cdot}".join(escaped)


def _tex_pairs(fig: Figure) -> str:
    """The accepting pairs as one math line, ``P = \\{([b],[b]), …\\}``."""
    keys = {nd.cls: nd.key for nd in fig.nodes}
    items = [rf"([{_tex_key(fig, keys[s])}],[{_tex_key(fig, keys[e])}])"
             for s, e in fig.pair_classes()]
    body = r",\; ".join(items) if items else r"\emptyset"
    return rf"$P = \{{\, {body} \,\}}$" if items else r"$P = \emptyset$"


def _loop_dirs(fig: Figure, pos: Placement) -> Dict[Tuple[int, int], str]:
    """A `loop <dir>` option for every self-loop edge, picked away from the node's
    neighbours: directions are scored by how many other nodes crowd their cone,
    least-crowded first (ties by the preference order), and a node carrying two
    self-loops takes two distinct directions."""
    out: Dict[Tuple[int, int], str] = {}
    for nd in fig.nodes:
        loops = sorted((e.letter_index for e in fig.edges
                        if e.src == nd.cls and e.is_loop))
        if not loops:
            continue
        x, y = pos[nd.cls]
        scored: List[Tuple[int, int, str]] = []
        for rank, (opt, (dx, dy)) in enumerate(LOOP_DIRS):
            crowd = 0
            for other in fig.nodes:
                if other.cls == nd.cls:
                    continue
                ox, oy = pos[other.cls]
                vx, vy = ox - x, oy - y
                dist = (vx * vx + vy * vy) ** 0.5
                if dist < CROWD_CM and (vx * dx + vy * dy) > 0.5 * dist:
                    crowd += 1
            scored.append((crowd, rank, opt))
        best = [opt for _, _, opt in sorted(scored)]
        for i, li in enumerate(loops):
            out[(nd.cls, li)] = best[i % len(best)]
    return out


def _bends(fig: Figure) -> Dict[Tuple[int, int], str]:
    """A `bend left=<angle>` option for every edge that shares its two endpoints
    with another edge (parallel or anti-parallel); the lone edge between two nodes
    stays straight. Both directions bend left, which is what separates an
    anti-parallel pair into the usual two arcs."""
    parallel: Dict[Tuple[int, int], List[int]] = {}
    for e in fig.edges:
        if not e.is_loop:
            parallel.setdefault((e.src, e.dst), []).append(e.letter_index)
    out: Dict[Tuple[int, int], str] = {}
    for (src, dst), letters in parallel.items():
        alone = len(letters) == 1 and (dst, src) not in parallel
        for i, li in enumerate(sorted(letters)):
            if not alone:
                out[(src, li)] = f"bend left={BEND_BASE + BEND_STEP * i}"
    return out


def tikz_of(fig: Figure, pos: Placement, provenance: str,
            pairs: bool = True) -> str:
    """The standalone `.tex` of ``fig`` placed at ``pos``; ``provenance`` is the
    command that produced it, recorded as the first line. ``pairs`` adds P as a
    caption node under the drawing — the object is ``<A, P>`` and only ``A`` has a
    shape, so P is typeset, not drawn."""
    tok = fig.naming.tokens()
    out: List[str] = [
        f"% {provenance}",
        "% Generated by sosl.sos.viz. Styles are centralized in the \\tikzset below:",
        "% edit a style to restyle, edit a coordinate to move a node.",
        r"\documentclass[tikz,border=4pt]{standalone}",
        r"\usetikzlibrary{arrows.meta,shapes.geometric}",
        r"\begin{document}",
        r"\begin{tikzpicture}[",
        r"  class/.style     = {draw, thin, ellipse, inner sep=1pt, "
        r"minimum width=9mm, minimum height=6.5mm},",
        r"  root/.style      = {dashed, draw=black!40, text=black!40},",
        r"  idem/.style      = {very thick},",
    ]
    for i, name in enumerate(fig.naming.names):
        dash = LETTER_DASH[i % len(LETTER_DASH)]
        out.append(f"  letter {tok[i]}/.style = {{{dash}}},"
                   f"           % display letter {name}")
    out += [
        r"  tree/.style      = {semithick, -{Stealth[length=4pt,width=3pt]}},",
        r"  nontree/.style   = {thin, -{Stealth[length=4pt,width=3pt]}},",
        r"  cyc/.style       = {double, double distance=0.8pt},",
        r"  pairs/.style     = {anchor=north, font=\small},",
        r"]",
        "",
    ]
    for nd in fig.nodes:
        style = "class" + (",root" if nd.is_root else "") + (",idem" if nd.is_idem else "")
        x, y = pos[nd.cls]
        out.append(f"  \\node[{style}] ({nd.ident}) at ({x:.1f},{y:.1f}) "
                   f"{{${_tex_key(fig, nd.key)}$}};")
    out.append("")

    loops, bends = _loop_dirs(fig, pos), _bends(fig)
    for e in fig.edges:
        style = [f"letter {tok[e.letter_index]}", "tree" if e.is_tree else "nontree"]
        if e.is_cycle:
            style.append("cyc")
        opt = loops.get((e.src, e.letter_index)) if e.is_loop \
            else bends.get((e.src, e.letter_index))
        via = f"[{opt}]" if opt else ""
        src, dst = fig.node_of(e.src).ident, fig.node_of(e.dst).ident
        out.append(f"  \\draw[{','.join(style)}] ({src}) to{via} ({dst});")

    if pairs:
        xs = [p[0] for p in pos.values()]
        low = min(p[1] for p in pos.values()) - PAIRS_DROP_CM
        mid = (min(xs) + max(xs)) / 2.0
        out += ["", f"  \\node[pairs] at ({mid:.1f},{low:.1f}) "
                    f"{{{_tex_pairs(fig)}}};"]

    out += [r"\end{tikzpicture}", r"\end{document}", ""]
    return "\n".join(out)
