"""``Pr_M(L)`` — the probability that a Markov chain's word is in ``L``.

Paper Theorem 3.5. The chain ``M`` is state-labelled (`mc.Chain`), the
language is held as an invariant, and the answer is an exact
`fractions.Fraction`.

The product walks ``states(M) x C`` from ``(q0, lambda(l(q0)))`` — the
initial state's letter is already folded in, matching the word semantics of
`mc` — with steps ``(q, c) -> (q', c . lambda(l(q')))``. Almost every run is
absorbed in a bottom SCC ``B`` of the product; there the run visits the
least ``M``-state ``q^`` of ``B`` infinitely often, so its word factors as a
stem into ``(q^, c)`` followed by infinitely many ``M``-cycles at ``q^``,
whose folds form the **cycle semigroup** ``T``. The generic verdict of ``B``
is then one table lookup ``theta_B = Val(c, k)`` against an idempotent ``k``
of the kernel of ``T`` — the §3 argument with ``T`` in place of ``S`` — and

    Pr_M(L) = sum_B theta_B * Pr[absorption in B]

by the same exact transient linear system as `measure`. See algorithm.md
§11.
"""
from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from typing import Dict, FrozenSet, List, Set, Tuple

from ..sos.alphabet import shortlex_key
from ..sos.calculus.table import Table
from ..sos.invariant import Invariant
from . import theta as _theta_mod
from .chain import assert_letters_leave_identity, least_key_class
from .kernel import _sccs
from .mc import Chain
from .measure import _solve

State = Tuple[int, int]
"""A product state: an ``M``-state and the class of the word read so far."""


@dataclass(frozen=True)
class ProductResult:
    """``Pr_M(L)`` with its certificate: the product's reachable size, and
    per bottom SCC (canonical order — by least ``(M-state, class key)``) the
    base state used, the generic verdict, and the absorption probability from
    the initial product state."""

    value: Fraction
    n_product: int
    bases: Tuple[int, ...]
    bits: Tuple[bool, ...]
    absorption: Tuple[Fraction, ...]


def _product(
    inv: Invariant, ch: Chain
) -> Tuple[State, Dict[State, Tuple[Tuple[State, Fraction], ...]]]:
    """The reachable product graph from ``(q0, lambda(l(q0)))``: for each
    reachable state its branches ``((successor, probability), ...)``."""
    lc = inv.letter_class
    init: State = (ch.init, lc[ch.label[ch.init]])
    succ: Dict[State, Tuple[Tuple[State, Fraction], ...]] = {}
    stack: List[State] = [init]
    while stack:
        st = stack.pop()
        if st in succ:
            continue
        q, c = st
        out: List[Tuple[State, Fraction]] = []
        for q2, pr in ch.trans[q]:
            d: State = (q2, inv.mult[c][lc[ch.label[q2]]])
            out.append((d, pr))
            if d not in succ:
                stack.append(d)
        succ[st] = tuple(out)
    return init, succ


def cycle_semigroup(inv: Invariant, ch: Chain, qhat: int) -> FrozenSet[int]:
    """The folds of the labels of ``M``'s cycles at ``qhat``: the classes
    collected at every return to ``qhat`` in a walk from ``(qhat, [eps])``
    over ``(M-state, class)`` pairs, each step reading the label of the state
    entered. Closed under product (a concatenation of cycles at ``qhat`` is a
    cycle at ``qhat``), hence a subsemigroup of ``S``."""
    lc = inv.letter_class
    start: State = (qhat, inv.identity)
    seen: Set[State] = {start}
    stack: List[State] = [start]
    out: Set[int] = set()
    while stack:
        q, c = stack.pop()
        for q2, _ in ch.trans[q]:
            c2 = inv.mult[c][lc[ch.label[q2]]]
            if q2 == qhat:
                out.add(c2)
            st: State = (q2, c2)
            if st not in seen:
                seen.add(st)
                stack.append(st)
    assert out, f"the M-state {qhat} lies on no cycle (it is not in a bottom SCC)"
    return frozenset(out)


def kernel_of(inv: Invariant, gens: FrozenSet[int]) -> FrozenSet[int]:
    """The kernel of the subsemigroup ``T = gens`` (which must be closed
    under product): the unique sink SCC of the two-sided Cayley graph on
    ``T`` generated by ``T`` itself — edges ``c -> t.c`` and ``c -> c.t``.
    Raises if ``T`` is not closed or the sink is not unique."""
    succs: Dict[int, List[int]] = {}
    for c in gens:
        out: Set[int] = set()
        for t in gens:
            out.add(inv.mult[t][c])
            out.add(inv.mult[c][t])
        assert out <= gens, (
            f"the cycle semigroup is not closed under product "
            f"(class {c} leaves it: {sorted(out - gens)})"
        )
        succs[c] = sorted(out)
    comps = _sccs(succs)
    comp_of: Dict[int, int] = {v: i for i, comp in enumerate(comps) for v in comp}
    sinks = [
        comp
        for i, comp in enumerate(comps)
        if all(comp_of[w] == i for v in comp for w in succs[v])
    ]
    assert len(sinks) == 1, (
        f"the two-sided Cayley graph of the cycle semigroup has {len(sinks)} "
        f"sink SCCs, expected exactly one (|T| = {len(gens)})"
    )
    return frozenset(sinks[0])


def _theta_at(
    inv: Invariant,
    ch: Chain,
    table: Table,
    members: List[State],
    qhat: int,
) -> bool:
    """The generic verdict of a product bottom SCC read at base state
    ``qhat``: ``Val(c, k)`` for the shortlex-least class ``c`` with
    ``(qhat, c)`` in the SCC and an idempotent ``k`` of the kernel of the
    cycle semigroup at ``qhat``. PARANOID re-reads it under a second kernel
    idempotent."""
    t_semi = cycle_semigroup(inv, ch, qhat)
    ker = kernel_of(inv, t_semi)
    k = inv.idempotent_power(least_key_class(inv, ker))
    assert inv.mult[k][k] == k, k
    assert k in ker, (k, sorted(ker))
    c = min(
        (cc for (q, cc) in members if q == qhat),
        key=lambda cc: shortlex_key(inv.keys[cc]),
    )
    bit = table.val(inv.accept, c, k)
    if _theta_mod.PARANOID and len(ker) > 1:
        t2 = max(ker, key=lambda x: shortlex_key(inv.keys[x]))
        k2 = inv.idempotent_power(t2)
        got = table.val(inv.accept, c, k2)
        assert got == bit, (
            f"theta differs across kernel idempotents at base state {qhat}: "
            f"{bit} under k={k}, {got} under k'={k2}"
        )
    return bit


def _theta(
    inv: Invariant, ch: Chain, table: Table, members: List[State]
) -> Tuple[int, bool]:
    """The base state and the generic verdict of one product bottom SCC.
    The base state is the least ``M``-state occurring in it; PARANOID
    re-derives the verdict from a second base state when the SCC has one."""
    qs = sorted({q for q, _ in members})
    qhat = qs[0]
    bit = _theta_at(inv, ch, table, members, qhat)
    if _theta_mod.PARANOID and len(qs) > 1:
        got = _theta_at(inv, ch, table, members, qs[1])
        assert got == bit, (
            f"theta differs across base states of a product bottom SCC: "
            f"{bit} at {qhat}, {got} at {qs[1]}"
        )
    return qhat, bit


def pr_chain(inv: Invariant, ch: Chain) -> ProductResult:
    """The exact probability that the word of the chain ``ch`` lies in the
    language of ``inv`` — ``Pr_M(L)`` of paper Theorem 3.5. Asserts the
    alphabets agree and that the absorption probabilities sum to 1."""
    assert ch.alphabet == inv.alphabet, (ch.alphabet.aps, inv.alphabet.aps)
    assert_letters_leave_identity(inv)
    ch.validate()
    table = Table.of(inv)
    init, succ = _product(inv, ch)

    states: List[State] = sorted(succ)
    idx: Dict[State, int] = {st: i for i, st in enumerate(states)}
    adj: Dict[int, List[int]] = {
        i: sorted({idx[d] for d, _ in succ[st]}) for i, st in enumerate(states)
    }
    comps = _sccs(adj)
    comp_of: Dict[int, int] = {v: i for i, comp in enumerate(comps) for v in comp}
    bottoms = [
        sorted(comp)
        for i, comp in enumerate(comps)
        if all(comp_of[w] == i for v in comp for w in adj[v])
    ]
    assert bottoms, "no bottom SCC in the product (it is finite)"
    bottoms.sort(
        key=lambda comp: min(
            (states[v][0], shortlex_key(inv.keys[states[v][1]])) for v in comp
        )
    )

    bases: List[int] = []
    bits: List[bool] = []
    for comp in bottoms:
        qhat, bit = _theta(inv, ch, table, [states[v] for v in comp])
        bases.append(qhat)
        bits.append(bit)

    where: Dict[int, int] = {v: j for j, comp in enumerate(bottoms) for v in comp}
    zero = Fraction(0)
    i0 = idx[init]
    if i0 in where:
        absorption = tuple(
            Fraction(1) if j == where[i0] else zero for j in range(len(bottoms))
        )
    else:
        transient = [i for i in range(len(states)) if i not in where]
        row_of = {v: r for r, v in enumerate(transient)}
        a = [[zero] * len(transient) for _ in transient]
        b = [[zero] * len(bottoms) for _ in transient]
        for v in transient:
            r = row_of[v]
            a[r][r] += 1
            for d, pr in succ[states[v]]:
                j = idx[d]
                if j in row_of:
                    a[r][row_of[j]] -= pr
                else:
                    b[r][where[j]] += pr
        absorption = tuple(_solve(a, b)[row_of[i0]])
    assert sum(absorption, zero) == 1, absorption
    value = sum((absorption[j] for j, bit in enumerate(bits) if bit), zero)
    return ProductResult(
        value=value,
        n_product=len(states),
        bases=tuple(bases),
        bits=tuple(bits),
        absorption=absorption,
    )
