"""Render the paper-facing enriched-monoid table of one algebra report.

Input: a machine report written by ``tests.sos.assemble`` (an ``EM(D) → S(L)₊``
section: one row per element with ``st``/``mk`` vectors, ``rmul`` ids, fold
class). Output: the same data in the paper's notation, one Markdown table —

    | ⟨w⟩ | at 0 | … | at n-1 | ·⟨b⟩ | ·⟨a⟩ | → class |

with per-state ``(target, marks)`` pairs (Definition 4.2 read directly),
right extensions named by element key word instead of id, classes in ``[·]``,
and letters renamed per ``--rename`` (paper convention ``a=a,!a=b``, the same
syntax as ``sos2cayley``). The identity row is dropped unless it also hosts a
nonempty class (an internal neutral element, e.g. EvenBlocks' ``⟨aa⟩ = ⟨ε⟩``),
in which case it is shown under that class's key word. Counts are therefore
semigroup counts: rows = ``|EM₊|``, fold targets = ``|𝒞|``.

Pure text processing — no Spot, no sosl import.
"""
from __future__ import annotations

import argparse
import re
from typing import Dict, List, Optional, Tuple

ROW_RE = re.compile(
    r"^\| (\d+) \| `([^`]+)` \| \[([^\]]*)\] \| \[([^\]]*)\] \| ([\d ]+) \| (.+) \|$")
CLASS_RE = re.compile(r"(\d+) `([^`]+)`")
MARKS_RE = re.compile(r"\{[^}]*\}")


def parse_rename(spec: Optional[str]) -> Dict[str, str]:
    """``'a=a,!a=b'`` as a letter map."""
    if not spec:
        return {}
    return dict(item.split("=", 1) for item in spec.split(","))


def rename_word(word: str, ren: Dict[str, str]) -> str:
    """A report key word (``;``-separated letters) in paper form (``·``-joined,
    letters renamed)."""
    return "·".join(ren.get(x, x) for x in word.split(";"))


class Row:
    def __init__(self, m: "re.Match[str]") -> None:
        self.id = int(m.group(1))
        self.word: str = m.group(2)
        self.st: List[str] = m.group(3).split()
        self.mk: List[str] = MARKS_RE.findall(m.group(4))
        self.rmul: List[int] = [int(x) for x in m.group(5).split()]
        self.classes: List[Tuple[int, str]] = [
            (int(i), k) for i, k in CLASS_RE.findall(m.group(6))]


def parse_em_rows(report: str) -> Tuple[List[Row], List[str]]:
    """The EM table rows of ``report`` and the letter order of its ``rmul``
    columns (read from the section's own caption line)."""
    section = report.split("### Enriched monoid")[1]
    letters_m = re.search(r"right-multiplication by each letter \(([^)]*)\)", section)
    if letters_m is None:
        raise ValueError("rmul letter-order caption not found")
    letters = re.findall(r"`([^`]+)`", letters_m.group(1))
    rows = [Row(m) for line in section.splitlines()
            if (m := ROW_RE.match(line.strip()))]
    if not rows:
        raise ValueError("no EM rows parsed")
    return rows, letters


def render(rows: List[Row], letters: List[str], ren: Dict[str, str]) -> str:
    """The paper table plus its one-line counts header."""
    def pair(st: str, mk: str) -> str:
        return f"({st}, {'∅' if mk == '{}' else mk})"

    def element_word(r: Row) -> str:
        if r.word != "eps":
            return rename_word(r.word, ren)
        hosted = [k for _, k in r.classes if k != "eps"]
        return rename_word(hosted[0], ren) if hosted else ""

    name_of: Dict[int, str] = {r.id: element_word(r) for r in rows}
    kept = [r for r in rows if name_of[r.id]]

    n_states = len(kept[0].st)
    heads = (["⟨w⟩"] + [f"at {q}" for q in range(n_states)]
             + [f"·⟨{ren.get(x, x)}⟩" for x in letters] + ["→ class"])
    lines = ["| " + " | ".join(heads) + " |",
             "|" + "|".join("---" for _ in heads) + "|"]
    for r in kept:
        fold = [k for _, k in r.classes if k != "eps"][0]
        cells = ([f"`⟨{name_of[r.id]}⟩`"]
                 + [f"`{pair(s, m)}`" for s, m in zip(r.st, r.mk)]
                 + [f"`⟨{name_of[t]}⟩`" for t in r.rmul]
                 + [f"`[{rename_word(fold, ren)}]`"])
        lines.append("| " + " | ".join(cells) + " |")

    n_classes = len({k for r in kept for _, k in r.classes if k != "eps"})
    counts = f"`|EM₊| = {len(kept)}` elements folding onto `|𝒞| = {n_classes}` classes."
    return counts + "\n\n" + "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("report", help="algebra report (tests.sos.assemble output)")
    ap.add_argument("--rename", help="letter rename map, e.g. 'a=a,!a=b'")
    ap.add_argument("--out", help="output file (default: print to stdout)")
    args = ap.parse_args()

    with open(args.report) as f:
        report = f.read()
    rows, letters = parse_em_rows(report)
    table = render(rows, letters, parse_rename(args.rename))
    body = (f"<!-- generated by em_table.py from {args.report}"
            " — do not edit -->\n" + table)
    if args.out:
        with open(args.out, "w") as f:
            f.write(body)
        print(f"wrote {args.out}")
    else:
        print(body)


if __name__ == "__main__":
    main()
