"""
kr/gap/aperiodic.py — the cheap GAP aperiodicity oracle (LTL-definability).

LTL == star-free == counter-free == the deterministic transition monoid is
APERIODIC (group-free). This module answers exactly that one question for a list
of generator images, with the MINIMAL GAP interaction: build the semigroup and
call `IsAperiodicSemigroup` — NO holonomy decomposition (that lives in
`gap/bridge.py` + `gap/export.py` and is the explosive step we want to AVOID when
the language is not LTL-definable in the first place).

It is the oracle the kr LtlTester (`kr/ltl_tester.py`) runs to GATE the cascade
build. Kept separate from the decomposition bridge on purpose: a different,
cheaper GAP script and a single boolean answer, no Cascade machinery.

Reuse, not modification: `_format_transformation` (GAP transformation syntax) and
`run_gap_script` (process spawn) are imported from their existing homes; this file
adds the aperiodicity-only script + its parse.
"""

from __future__ import annotations

from typing import List

from .export import _format_transformation
from .runner import run_gap_script


def _aperiodicity_script(generators: List[List[int]]) -> str:
    """A minimal self-contained GAP script: load Semigroups, build the semigroup
    from `generators`, print its size and `IsAperiodicSemigroup`. No SgpDec /
    holonomy. (`IsAperiodicSemigroup` lives in the Semigroups package.)"""
    body = ",\n    ".join(_format_transformation(g) for g in generators)
    return (
        '# Auto-generated by BuchiToLTL/kr/gap/aperiodic.py (LTL-definability oracle).\n'
        'LoadPackage("Semigroups");\n'
        f'gens := [\n    {body}\n];\n'
        'T := Semigroup(gens);\n'
        'Print("SEMI_GROUP_SIZE: ", Size(T), "\\n");\n'
        'Print("APERIODIC: ", IsAperiodicSemigroup(T), "\\n");\n'
        'QUIT;\n'
    )


def is_aperiodic_gens(
    generators: List[List[int]],
    *,
    gap_cmd: str = "gap",
    timeout: int = 30,
) -> bool:
    """True iff the transition monoid generated by `generators` is aperiodic
    (group-free) — i.e. the language is LTL / star-free / counter-free.

    `generators` is a non-empty list of equal-length image lists (0-based), the
    same representation `extract_generators` produces. Raises `ValueError` on an
    empty list and `RuntimeError` if GAP does not report a verdict.
    """
    if not generators:
        raise ValueError("at least one generator is required")
    raw = run_gap_script(
        _aperiodicity_script(generators), gap_cmd=gap_cmd, timeout=timeout
    )
    for line in raw.splitlines():
        if line.startswith("APERIODIC:"):
            return line.partition(":")[2].strip() == "true"
    raise RuntimeError(f"GAP did not report an APERIODIC verdict; output:\n{raw[:400]}")


__all__ = ["is_aperiodic_gens"]
