"""
kr/gap/export.py — GAP source generation (the "ugly string" service).

Turns a list of transformation images into a self-contained GAP script that
loads SgpDec, builds the semigroup, computes the holonomy cascade, and emits a
structured block that kr/gap/parse.py can read back. This is deliberately
isolated: it is verbose, GAP-dialect-specific string assembly with no I/O and
no dependency on the rest of the package, so it stays out of the pure module API
in bridge.py.

The generated script uses easy-to-parse Print statements (CASCADE_START /
KEY: value + STATE ... CONFIG lines), keeping the Python side robust against
small changes in SgpDec pretty-printers.
"""

from __future__ import annotations
from typing import List


def _format_transformation(images: List[int]) -> str:
    """Return GAP source for Transformation([1-based images...])."""
    # GAP Transformations are 1-based.
    one_based = [i + 1 for i in images]
    return f"Transformation({one_based})"


def generate_gap_script(
    generators: List[List[int]],
    *,
    title: str = "BuchiToLTL KR decomposition",
    max_runtime_seconds: int = 120,
) -> str:
    """
    Produce a complete, self-contained GAP script.

    The script:
      1. Loads SgpDec (fails loudly if missing).
      2. Builds the semigroup from the generators.
      3. Computes the holonomy cascade.
      4. Emits a structured block that is easy to parse from Python.

    The caller is responsible for writing the script to disk and running `gap`.
    """
    if not generators:
        raise ValueError("At least one generator is required")

    n = len(generators[0])
    for g in generators:
        if len(g) != n:
            raise ValueError("All generators must have the same domain size")

    lines: List[str] = []
    lines.append('########################################################################')
    lines.append(f'# {title}')
    lines.append('# Auto-generated by BuchiToLTL/kr/gap/export.py')
    lines.append('# Do not edit by hand — re-run the Python generator instead.')
    lines.append('########################################################################')
    lines.append('')
    lines.append('LoadPackage("SgpDec");')
    lines.append('')
    lines.append('# Deterministic runs: AsHolonomyCoords picks a RandomChain through each')
    lines.append('# point, so unseeded runs produce different (equally valid) lifts and')
    lines.append('# coordinate-dependent bugs become heisenbugs. Fix both GAP sources.')
    lines.append('Reset(GlobalMersenneTwister, 0);;')
    lines.append('Reset(GlobalRandomSource, 0);;')
    lines.append('')
    lines.append('# === Generated generators (1-based images for GAP) ===')
    lines.append('gens := [')
    for i, g in enumerate(generators):
        comma = "," if i < len(generators) - 1 else ""
        lines.append(f'    {_format_transformation(g)}{comma}   # letter {i}')
    lines.append('];')
    lines.append('')
    lines.append('T := Semigroup(gens);')
    lines.append(f'n_states := {n};   # reliable domain size from generator images (SgpDec Degree may be 0 for 1-el)')
    lines.append('Print("SEMI_GROUP_SIZE: ", Size(T), "\\n");')
    lines.append('Print("NUM_STATES: ", n_states, "\\n");')
    lines.append('')
    lines.append('# === Holonomy cascade (the expensive step) ===')
    lines.append('# Guard: SgpDec HolonomyCascadeSemigroup can crash or misreport Degree=0 on 1-state (trivial) TS.')
    lines.append('if n_states <= 1 then')
    lines.append('  # Trivial case handled below without calling Holonomy.')
    lines.append('else')
    lines.append('  hcs := HolonomyCascadeSemigroup(T);')
    lines.append('fi;')
    lines.append('')
    lines.append('Print("CASCADE_START\\n");')
    lines.append('')
    lines.append('# Robust extraction for SgpDec 1.x (no reliance on internal !.Levels record).')
    lines.append('# Number of levels = length of a coordinate tuple.')
    lines.append('n := n_states;')
    lines.append('if n <= 1 then')
    lines.append('  if n = 0 then')
    lines.append('    Print("NUM_LEVELS: 0\\n");')
    lines.append('  else')
    lines.append('    # Trivial 1-state cascade: 1 level, coord [1] (1-based as SgpDec uses).')
    lines.append('    Print("NUM_LEVELS: 1\\n");')
    lines.append('    Print("LEVEL 0 SIZE 1 KIND reset\\n");')
    lines.append('    Print("STATE_MAP_START\\n");')
    lines.append('    Print("STATE 0 CONFIG [ 1 ]\\n");')
    lines.append('    Print("STATE_MAP_END\\n");')
    lines.append('  fi;')
    lines.append('else')
    lines.append('  # True holonomy coordinatization via the skeleton. NOTE: AsCoords(s, hcs)')
    lines.append('  # is DomainOf(hcs)[s] — the s-th tuple of the domain ENUMERATION, unrelated')
    lines.append('  # to point s. The lift of a point is AsHolonomyCoords(s, sk); the cover map')
    lines.append('  # pi (coords -> point) is AsHolonomyPoint(c, sk). pi is many-to-one, so the')
    lines.append('  # config dynamics CANNOT be reconstructed through the lift: we emit the')
    lines.append('  # genuine cascade transitions (lifted generators acting via OnCoordinates)')
    lines.append('  # on the BFS closure of the state lifts, plus pi for every closure config.')
    lines.append('  sk := SkeletonOf(hcs);')
    lines.append('  all_coords := List([1..n], s -> AsHolonomyCoords(s, sk));')
    lines.append('  num_lev := Length(all_coords[1]);')
    lines.append('  Print("NUM_LEVELS: ", num_lev, "\\n");')
    lines.append('  # Per-level sizes: true component domain sizes (not max observed coord)')
    lines.append('  compdoms := ComponentDomains(hcs);')
    lines.append('  for lev in [1..num_lev] do')
    lines.append('    Print("LEVEL ", lev-1, " SIZE ", Size(compdoms[lev]), " KIND reset\\n");')
    lines.append('  od;')
    lines.append('  # State -> configuration lift (h section of pi)')
    lines.append('  Print("STATE_MAP_START\\n");')
    lines.append('  for s in [1..n] do')
    lines.append('    coord := all_coords[s];')
    lines.append('    Print("STATE ", s-1, " CONFIG ", coord, "\\n");')
    lines.append('  od;')
    lines.append('  Print("STATE_MAP_END\\n");')
    lines.append('  # True cascade transitions: BFS closure of state lifts under lifted gens')
    lines.append('  lifts := List(gens, g -> AsHolonomyCascade(g, sk));')
    lines.append('  visited := Set(ShallowCopy(all_coords));')
    lines.append('  frontier := ShallowCopy(visited);')
    lines.append('  Print("TRANS_START\\n");')
    lines.append('  while Length(frontier) > 0 do')
    lines.append('    c := Remove(frontier);')
    lines.append('    for i in [1..Length(lifts)] do')
    lines.append('      c2 := OnCoordinates(c, lifts[i]);')
    lines.append('      Print("TRANS ", c, " GEN ", i-1, " TO ", c2, "\\n");')
    lines.append('      if not c2 in visited then')
    lines.append('        AddSet(visited, c2);')
    lines.append('        Add(frontier, c2);')
    lines.append('      fi;')
    lines.append('    od;')
    lines.append('  od;')
    lines.append('  Print("TRANS_END\\n");')
    lines.append('  # pi (cover map) for every closure config: acceptance/Muller lifting')
    lines.append('  Print("PI_START\\n");')
    lines.append('  for c in visited do')
    lines.append('    Print("PI ", c, " POINT ", AsHolonomyPoint(c, sk)-1, "\\n");')
    lines.append('  od;')
    lines.append('  Print("PI_END\\n");')
    lines.append('fi;')
    lines.append('')
    lines.append('Print("CASCADE_END\\n");')
    lines.append('')
    lines.append('# Friendly one-liner for humans')
    lines.append('if n_states > 0 then')
    lines.append('  if n_states <= 1 then')
    lines.append('    Print("Holonomy cascade ready (trivial 1-state).\\n");')
    lines.append('  else')
    lines.append('    Print("Holonomy cascade ready. Levels: ", Length(AsHolonomyCoords(1, SkeletonOf(hcs))), "\\n");')
    lines.append('  fi;')
    lines.append('else')
    lines.append('  Print("Holonomy cascade ready (trivial).\\n");')
    lines.append('fi;')
    lines.append('QUIT;')
    lines.append('')

    return "\n".join(lines)
