"""The recognition frame — the value one synthesis recursion node runs on.

A frame instantiates the contract of `algorithm.md` layer 2: an abstract
alphabet (letters `0..k-1`), a morphism into a finite monoid given by its
multiplication table (the letter images), and the ω-class calculus of layer 6
materialized — the letter-generated subsemigroup with a shortlex-least
non-empty letter word per element, the linked pairs over it, and their
conjugacy classes (the frame's ω-classes, each keyed by its least member
pair). A `Target` presents a recognized language over a frame by its
`≈`-classes: the ε flag, the finite-word fibers (a set of monoid elements),
and a set of the frame's ω-class ids.

The root frame reads the invariant `𝓘(L)` directly (`root_frame`): root
letters are the concrete letters (masks over `AP`), their images the letter
classes, the monoid the class multiplication table. Every deeper frame is
built by `compress` over a sub-alphabet or the compressed alphabet. All ids
are canonical: elements keep the monoid's ids, ω-classes are ordered by
least member pair — so equal frames mean equal enumerations everywhere
downstream.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, FrozenSet, List, Sequence, Tuple, TYPE_CHECKING

if TYPE_CHECKING:
    from sosl.sos import Invariant

Word = Tuple[int, ...]
"""A word as 0-based letter indices into a frame's alphabet."""

Pair = Tuple[int, int]
"""A linked pair `(s, e)` of monoid elements: `s·e = s`, `e·e = e`."""


@dataclass(eq=False)
class Frame:
    """One recursion node's alphabet, morphism, and ω-class universe.

    Treat as immutable (identity equality; the dict fields are lookups, not
    state). `gen` is the subsemigroup generated by the letter images —
    non-empty products only, so it contains the unit exactly when some
    non-empty word reaches it. `rep[el]` is the shortlex-least *non-empty*
    letter word for `el ∈ gen` (shortlex = the letter index order).
    """

    images: Tuple[int, ...]                 # letter -> monoid element
    mult: Tuple[Tuple[int, ...], ...]       # element × element -> element
    unit: int                               # the monoid identity
    gen: Tuple[int, ...]                    # ⟨images⟩⁺, ascending element ids
    rep: Dict[int, Word]                    # gen element -> shortlex letter word
    pairs: Tuple[Pair, ...]                 # linked pairs over gen, (s,e) ascending
    pair_cls: Dict[Pair, int]               # pair -> ω-class id
    omega: Tuple[Tuple[Pair, ...], ...]     # ω-class id -> member pairs, ascending

    def n_letters(self) -> int:
        return len(self.images)


@dataclass(frozen=True)
class Target:
    """A recognized language over a frame, presented by its `≈`-classes."""

    eps: bool                # is the empty word in the language
    fin: FrozenSet[int]      # fibers: non-empty finite words with these images
    om: FrozenSet[int]       # ω-class ids of the frame


def make_frame(images: Sequence[int], mult: Sequence[Sequence[int]],
               unit: int) -> Frame:
    """Build the frame of an alphabet: closure, pairs, conjugacy classes.

    The subsemigroup BFS enumerates non-empty words shortest-first in letter
    order, so the first word reaching an element is its shortlex-least one.
    Conjugacy of linked pairs — `∃ x, y ∈ S¹: e = x·y, e′ = y·x, s′ = s·x`
    ([PP] Prop 2.6, an equivalence) — is tested against one representative
    per class; classes are created in ascending pair order, so class ids are
    ordered by least member pair.
    """
    rep: Dict[int, Word] = {}
    frontier: List[int] = []
    for li, im in enumerate(images):
        if im not in rep:
            rep[im] = (li,)
            frontier.append(im)
    while frontier:
        nxt: List[int] = []
        for el in frontier:
            w: Word = rep[el]
            for li, im in enumerate(images):
                p: int = mult[el][im]
                if p not in rep:
                    rep[p] = w + (li,)
                    nxt.append(p)
        frontier = nxt
    gen: Tuple[int, ...] = tuple(sorted(rep))

    pairs: Tuple[Pair, ...] = tuple(
        (s, e) for s in gen for e in gen
        if mult[e][e] == e and mult[s][e] == s)

    sone: List[int] = list(gen) if unit in rep else [unit] + list(gen)

    def conjugate(p: Pair, q: Pair) -> bool:
        s, e = p
        s2, e2 = q
        return any(mult[x][y] == e and mult[y][x] == e2 and mult[s][x] == s2
                   for x in sone for y in sone)

    pair_cls: Dict[Pair, int] = {}
    omega: List[List[Pair]] = []
    for p in pairs:
        for cid, members in enumerate(omega):
            if conjugate(p, members[0]):
                pair_cls[p] = cid
                members.append(p)
                break
        else:
            pair_cls[p] = len(omega)
            omega.append([p])

    mt: Tuple[Tuple[int, ...], ...] = tuple(tuple(row) for row in mult)
    return Frame(images=tuple(images), mult=mt, unit=unit, gen=gen, rep=rep,
                 pairs=pairs, pair_cls=pair_cls,
                 omega=tuple(tuple(ms) for ms in omega))


def root_frame(inv: "Invariant") -> Frame:
    """The root node's frame: the concrete letters (masks, ascending) acting
    on the class algebra. The identity is fresh — no non-empty word reaches
    it — so it never enters the letter-generated subsemigroup; asserted, as
    the base-case and divisor arguments lean on it at the root."""
    frame: Frame = make_frame(tuple(inv.letter_class), inv.mult, inv.identity)
    assert inv.identity not in frame.gen, \
        "a non-empty word reached the fresh identity: malformed invariant"
    return frame


def root_target(inv: "Invariant", frame: Frame) -> Target:
    """The root target: `L` itself — no ε, no finite words, the accepting
    ω-classes. Asserts the query-independence lemma of `algorithm.md`
    layer 6 on the ground data: `P` is constant across each conjugacy class.
    """
    linked: FrozenSet[Pair] = inv.linked_pairs()
    om: List[int] = []
    for cid, members in enumerate(frame.omega):
        assert all(p in linked for p in members), \
            "a frame pair is not linked in the invariant"
        values = {p in inv.accept for p in members}
        assert len(values) == 1, \
            "P varies inside a conjugacy class: query independence violated"
        if values.pop():
            om.append(cid)
    return Target(eps=False, fin=frozenset(), om=frozenset(om))


__all__ = ["Word", "Pair", "Frame", "Target", "make_frame",
           "root_frame", "root_target"]
