"""Generate the named-case campaigns' manifest from the committed artifacts.

    python3 -m tests.sosl.campaign_manifest [--out ../reference/campaigns/README.md]

The named-case campaigns (E0, M4B, E5) run a handful of hand-chosen specimens rather
than the catalogue, and each is a gate: it asserts a property and exits nonzero if it
breaks. Their committed outputs are the paper's evidence for the worked examples.

Recomputes every figure it prints from the `results.csv` beside each campaign —
nothing is carried in this file, so the manifest cannot drift from the data. A build
product; never hand-edited.
"""
from __future__ import annotations

import csv
import subprocess
import sys
from collections import Counter
from datetime import date
from pathlib import Path
from typing import List, NamedTuple

REF = Path("../reference/campaigns")


class Campaign(NamedTuple):
    """A named-case campaign: its directory, the module that regenerates it, and
    the claim its gate enforces."""
    name: str
    module: str
    claim: str
    artifacts: str


CAMPAIGNS: List[Campaign] = [
    Campaign("e0", "tests.sosl.campaign_e0",
             "The E0 gate: zero failures, zero budget overruns, zero crashes on the "
             "named specimens. Every case learns the canonical invariant byte-equal "
             "to its reference, and the Even/EvenBlocks ledgers are byte-stable "
             "(row P5).",
             "results.csv, e0_report.md, e4_transcripts.md"),
    Campaign("m4b", "tests.sosl.campaign_m4b",
             "The E1 cost bound holds on the named cases, and the E2 stall classes "
             "match theory (the permanent specimens are `a_implies_xa`, `a_once`).",
             "results.csv, e1_report.md, e2_report.md"),
    Campaign("e5", "tests.sosl.campaign_e5",
             "Counterexample padding preserves the invariant — only cost changes: "
             "every policy learns the same object, so `cex-first` is as sound as "
             "`cex-minimal`.",
             "results.csv, e5_report.md"),
]


def _git_rev() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True,
                              check=True).stdout.strip()
    except Exception:  # noqa: BLE001 -- a manifest is still valid outside a checkout
        return "unknown"


def _section(c: Campaign) -> str:
    path = REF / c.name / "results.csv"
    if not path.exists():
        return f"## `{c.name}/` — MISSING (`{path}` not found)\n"
    with open(path, newline="") as fh:
        rows = list(csv.DictReader(fh))
    cases = sorted({r["case_id"] for r in rows})
    configs = sorted({r["config_id"] for r in rows})
    verdicts = dict(sorted(Counter(r["verdict"] for r in rows).items()))
    tally = ", ".join(f"**{v}** {n}" for v, n in verdicts.items())
    return f"""## `{c.name}/`

{c.claim}

- {len(rows)} runs = {len(cases)} case(s) x {len(configs)} config(s)
- verdicts: {tally}
- cases: {', '.join(f'`{x}`' for x in cases)}
- configs: {', '.join(f'`{x}`' for x in configs)}
- artifacts: `{c.artifacts}`

Regenerate (from `sosl/`) — the campaign is its own gate, so a nonzero exit *is* the
failure report:

```
python3 -m {c.module}
```
"""


def main(argv: List[str]) -> int:
    out = Path(argv[argv.index("--out") + 1]) if "--out" in argv else REF / "README.md"
    body = "\n".join(_section(c) for c in CAMPAIGNS)
    text = f"""# Named-case campaigns — the committed record

Generated by `python3 -m tests.sosl.campaign_manifest` (from `sosl/`) — a build
product, not a hand-edited file. Every figure below is recomputed from the
`results.csv` in each directory.

- date: {date.today().isoformat()}
- git: {_git_rev()}

These campaigns run hand-chosen specimens, not the catalogue (that is
`reference/census/`). Each is a **gate**: it asserts its claim and exits nonzero if
it breaks, so re-running it is both the reproduction and the check. Unlike the
census, they do not depend on the corpus, so a re-run *is* a reproduction.

{body}"""
    out.write_text(text)
    print(f"wrote {out}: {len(CAMPAIGNS)} campaigns", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
