"""Generate the census record's manifest from the committed artifacts.

    python3 -m tests.sosl.census_manifest [--out ../reference/census/README.md]

Recomputes every figure it prints from the CSVs beside it — nothing is carried in
this file, so the manifest cannot drift from the data it describes. Reads
`sweep_results.csv` (the learner sweep, keyed `case_id,config_id`) and
`e3_assembled.csv` (the ROLL baseline, keyed `case,kind`), and states for each the
command that reproduces it.

Run it after installing a new drop into `reference/census/`; the manifest is a
build product, never hand-edited.
"""
from __future__ import annotations

import csv
import subprocess
import sys
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Dict, List, Tuple

REF = Path("../reference/census")


def _git_rev() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True,
                              check=True).stdout.strip()
    except Exception:  # noqa: BLE001 -- a manifest is still valid outside a checkout
        return "unknown"


def _rows(path: Path) -> List[dict]:
    with open(path, newline="") as fh:
        return list(csv.DictReader(fh))


def _dup_count(rows: List[dict], key: Tuple[str, ...]) -> int:
    keys = [tuple(r[c] for c in key) for r in rows]
    return len(keys) - len(set(keys))


def _verdict_table(rows: List[dict]) -> str:
    legs = sorted({r["config_id"] for r in rows})
    verdicts = sorted({r["verdict"] for r in rows})
    out = ["| leg | " + " | ".join(verdicts) + " | total |",
           "|---|" + "--:|" * (len(verdicts) + 1)]
    for leg in legs:
        c = Counter(r["verdict"] for r in rows if r["config_id"] == leg)
        cells = " | ".join(str(c.get(v, 0)) for v in verdicts)
        out.append(f"| `{leg}` | {cells} | {sum(c.values())} |")
    return "\n".join(out)


def main(argv: List[str]) -> int:
    out = Path(argv[argv.index("--out") + 1]) if "--out" in argv else REF / "README.md"
    sweep_p, e3_p = REF / "sweep_results.csv", REF / "e3_assembled.csv"
    sweep, e3 = _rows(sweep_p), _rows(e3_p)

    sw_cases = {r["case_id"] for r in sweep}
    e3_cases = {r["case"] for r in e3}
    kinds: Dict[str, int] = dict(sorted(Counter(r["kind"] for r in e3).items()))
    sw_dups = _dup_count(sweep, ("case_id", "config_id"))
    e3_dups = _dup_count(e3, ("case", "kind"))

    text = f"""# Census — the committed record

Generated by `python3 -m tests.sosl.census_manifest` (from `sosl/`) — a build
product, not a hand-edited file. Every figure below is recomputed from the CSVs in
this directory.

- date: {date.today().isoformat()}
- git: {_git_rev()}
- corpus: `genaut/corpus/flat_canon` — **{len(sw_cases)} languages**

These CSVs are the reproducible source for the paper's census figures. The corpus
grows, so a re-run is not a reproduction of an earlier drop — the committed file is.
Drops are additive (`--done`), so this record is the union of every drop so far.

## `sweep_results.csv` — the learner sweep

{len(sweep)} rows = {len(sw_cases)} languages x {len(sweep) // max(len(sw_cases), 1)} legs, keyed `(case_id, config_id)`; **{sw_dups} duplicate keys**.

{_verdict_table(sweep)}

Reproduce (from `sosl/`) — the sweep is a cluster campaign, planned additively
against this very file, so a fresh drop runs only the languages it does not yet hold:

```
OARRUN_TIMEOUT=300 python3 -m tests.sosl.cluster_plan \\
    --done ../reference/census/sweep_results.csv -o tests/sosl/logs/cluster/sweep.cmds
cluster/oarrun.sh --timeout 300 --cores 4 --split 250 sosl/tests/sosl/logs/cluster/sweep.cmds
cluster/reap_until.sh "$RUN"
python3 -m tests.sosl.merge_drops --key case_id,config_id -o <merged> \\
    ../reference/census/sweep_results.csv ../logs/cluster/<RUN>/results.csv
```

Analysis (E1 — soundness + per-N cost, `e1_summary.md`):

```
python3 -m tests.sosl.census_e1 ../reference/census/sweep_results.csv
```

## `e3_assembled.csv` — the ROLL FDFA baseline

{len(e3)} rows = {len(e3_cases)} languages x {len(kinds)} kinds ({', '.join(f'`{k}` {v}' for k, v in kinds.items())}), keyed `(case, kind)`; **{e3_dups} duplicate keys**.

`ours` is **derived from the sweep**, never re-run: our `N` is the config-independent
`ref_classes`, and its MQ/EQ are the default leg's `n_member_total`/`n_equiv`. ROLL's
three kinds are the cluster campaign.

Reproduce (from `sosl/`):

```
OARRUN_TIMEOUT=300 python3 -m tests.sosl.cluster_plan --e3 \\
    --done ../reference/census/e3_assembled.csv -o tests/sosl/logs/cluster/e3.cmds
# ... oarrun / reap_until / merge_drops --key case,kind ...
python3 -m tests.sosl.census_e3 --from-sweep ../reference/census/sweep_results.csv \\
    --out-csv <merged>          # the `ours` rows
```

Analysis (E3 — paired medians + the LTL cut, `e3_summary.md`):

```
python3 -m tests.sosl.census_e3 --summary-only --out-csv ../reference/census/e3_assembled.csv
```

## Summaries

`e1_summary.md` and `e3_summary.md` are the analyzers' own output, regenerated by the
two analysis commands above.
"""
    out.write_text(text)
    print(f"wrote {out}: {len(sw_cases)} languages, sweep {len(sweep)} rows "
          f"({sw_dups} dup), e3 {len(e3)} rows ({e3_dups} dup)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
