#!/usr/bin/env python3
"""
Synthetic example for the KR / SgpDec bridge.

This does not require a real GAP + SgpDec installation for the "show the script"
part.  With GAP installed it will also run a tiny decomposition.

Run:
    python3 -m kr.examples.synthetic
    # or after chmod +x
    ./kr/examples/synthetic.py
"""

import sys
from pathlib import Path

# Make sure we can import the kr package when run directly
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from aut2ltl.kr.gap_bridge import generate_gap_script, check_gap_available, decompose_gens
from aut2ltl.kr.cascade import Cascade, LevelInfo


def main():
    # A very small transformation semigroup: the symmetric group on 3 points
    # generated by a transposition and a 3-cycle.
    # Images are 0-based (we convert inside the generator).
    gen0 = [1, 0, 2]   # (0 1)
    gen1 = [1, 2, 0]   # (0 1 2)
    gens = [gen0, gen1]

    print("=== Generators (0-based images) ===")
    for i, g in enumerate(gens):
        print(f"  letter {i}: {g}")

    script = generate_gap_script(gens, title="Synthetic S3 example")
    print("\n=== Generated GAP script (first 30 lines) ===")
    for i, line in enumerate(script.splitlines()[:30], 1):
        print(f"{i:3d}: {line}")
    print("... (truncated)")

    print("\n=== GAP availability check ===")
    if check_gap_available():
        print("GAP + SgpDec appears to be loadable. Running the decomposition...")
        try:
            casc = decompose_gens(gens, timeout=60)
            print("SUCCESS:", casc)
            print("state_to_config:", casc.state_to_config)
            print("has nontrivial groups?", casc.has_nontrivial_groups())
        except Exception as e:
            print("Run failed (this is expected if SgpDec is not fully set up):", e)
    else:
        print("No usable GAP + SgpDec in PATH.")
        print("Run ./kr/install.sh (or install manually) and try again.")
        # Still return a dummy Cascade so the example is always runnable.
        dummy = Cascade(
            num_levels=2,
            levels=[LevelInfo(index=0, size=2, kind="reset"),
                    LevelInfo(index=1, size=3, kind="group", structure="S3")],
            num_states=3,
            state_to_config={0:(1,1), 1:(2,1), 2:(3,2)},
        )
        print("Returning a synthetic Cascade for illustration:", dummy)


if __name__ == "__main__":
    main()
