"""The acceptance-enriched monoid's elements — Key I of the construction.

The transition monoid of a deterministic automaton forgets the acceptance
marks a run collects along its way — exactly the data an Emerson-Lei condition
consumes. The **enriched element** of a finite word ``w`` maps each state ``q``
to the pair ``(delta(q, w), marks collected from q along w)``; elements
compose as

    (f, M) . (g, N) : q -> ( g(f(q)), M(q) | N(f(q)) )

so the enriched monoid ``EM(D)`` is a finite transformation monoid on
``Q x 2^C`` (``C`` the acceptance marks), generated by the letter elements.
Two words with equal enriched elements induce identical run skeletons from
every state — same states at block boundaries, same marks per block — hence
equal acceptance inside any lasso context (the skeleton lemma). That is what
makes ``EM(D)`` a recognizer of the language where the bare transition monoid
is not.

This module holds the element value and its two constructors: composition,
and the letter elements read off a deterministic complete ``spot.twa_graph``,
indexed by an `Alphabet`'s letter masks (canonical letter order).
"""
from __future__ import annotations

from typing import FrozenSet, List, Optional, Tuple

import buddy
import spot

from ..alphabet import Alphabet, Letter

# One enriched element: per state, (destination, marks collected on the way).
Elem = Tuple[Tuple[int, FrozenSet[int]], ...]


def identity_elem(n_states: int) -> Elem:
    """The enriched element of the empty word: ``q -> (q, {})``."""
    return tuple((q, frozenset()) for q in range(n_states))


def compose(e1: Elem, e2: Elem) -> Elem:
    """The enriched element of ``w1.w2`` from those of ``w1`` and ``w2``."""
    return tuple((e2[dst][0], marks | e2[dst][1]) for (dst, marks) in e1)


def letter_formula(alphabet: Alphabet, a: Letter) -> str:
    """Letter ``a`` rendered as a full Boolean cube over the alphabet's
    propositions, e.g. ``a & !b`` (``t`` when there are none)."""
    trues = set(alphabet.true_aps(a))
    lits = [(ap if ap in trues else f"!{ap}") for ap in alphabet.aps]
    return " & ".join(lits) if lits else "t"


def letter_elems(aut: "spot.twa_graph", alphabet: Alphabet) -> List[Elem]:
    """The enriched element of every letter, in alphabet mask order.

    ``aut`` must be deterministic and complete over exactly the alphabet's
    propositions: for every state and letter, one and only one outgoing edge
    fires. Raises ``ValueError`` otherwise (no silent choice, no silent stall).
    """
    n: int = aut.num_states()
    d = aut.get_dict()
    elems: List[Elem] = []
    for a in alphabet.letters():
        cube = spot.formula_to_bdd(spot.formula(letter_formula(alphabet, a)), d, aut)
        entry: List[Tuple[int, FrozenSet[int]]] = []
        for s in range(n):
            hit: Optional[Tuple[int, FrozenSet[int]]] = None
            for e in aut.out(s):
                if (e.cond & cube) != buddy.bddfalse:
                    if hit is not None:
                        raise ValueError(
                            f"state {s}: two edges fire for letter "
                            f"{letter_formula(alphabet, a)} (not deterministic)")
                    hit = (e.dst, frozenset(e.acc.sets()))
            if hit is None:
                raise ValueError(
                    f"state {s}: no edge for letter "
                    f"{letter_formula(alphabet, a)} (not complete)")
            entry.append(hit)
        elems.append(tuple(entry))
    return elems


__all__ = ["Elem", "identity_elem", "compose", "letter_formula", "letter_elems"]
